import Head from 'next/head'
import HomeCover from 'templates/home/HomeCover'
import HomeAcademy from 'templates/home/HomeAcademy'
import HomeNews from 'templates/home/HomeNews'
import HomeSocio from 'templates/home/HomeSocio'
import HomePromo from 'templates/home/HomePromo'
import HomeSlider from 'templates/home/HomeSlider'
import HomeServicios from 'templates/home/HomeServicios'
import { GetStaticProps } from 'next'

import {
  useQuery,
  prepareReactRender,
  useHydrateCache,
  ENUM_SERVICIO_CATEGORIA,
} from 'client'
import { PropsWithServerCache } from '@gqty/react'

type HomeProps = PropsWithServerCache<{}>
const Home = ({ cacheSnapshot }: HomeProps) => {
  const query = useQuery()
  const home = query.homepage.data.attributes
  const posts = query.articles({
    pagination: {
      pageSize: 3,
    },
  }).data
  const slides = query.slides().data
  const servicios = query.servicios({
    pagination: {
      pageSize: 100,
    },
    filters: {
      categoria: {
        in: [
          ENUM_SERVICIO_CATEGORIA.ahorro,
          ENUM_SERVICIO_CATEGORIA.prestamos,
          ENUM_SERVICIO_CATEGORIA.facilidades,
        ],
      },
    },
  }).data

  useHydrateCache({
    cacheSnapshot,
  })

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomeCover portada={home?.portada} />
        <HomeSlider slides={slides} />
        <HomeServicios {...{ servicios }} />
        <HomeSocio {...{ home }} />
        <HomeAcademy posts={posts} />
        <HomeNews noticias={posts} />
        <HomePromo {...{ home }} />
      </main>
    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps<HomeProps> = async (_ctx) => {
  const { cacheSnapshot } = await prepareReactRender(<Home />)

  return {
    props: { cacheSnapshot },
  }
}
