import Head from "next/head";
import HomeCover from "templates/home/HomeCover";
import HomeAcademy from "templates/home/HomeAcademy";
import HomeNews from "templates/home/HomeNews";
import HomeSocio from "templates/home/HomeSocio";
import HomePromo from "templates/home/HomePromo";
import HomeSlider from "templates/home/HomeSlider";
import HomeServicios from "templates/home/HomeServicios";
import { GetStaticProps } from "next";
import Layout from "components/Layout";

import {
  useQuery,
  prepareReactRender,
  useHydrateCache,
  ENUM_SERVICIO_CATEGORIA,
} from "client";
import { PropsWithServerCache } from "@gqty/react";
import Loading from "components/loading";

type HomeProps = PropsWithServerCache<{}>;
const Home = ({ cacheSnapshot }: HomeProps) => {
  useHydrateCache({
    cacheSnapshot,
  });

  const query = useQuery();
  const home = query?.homepage?.data?.attributes;
  const posts = query.articles({
    pagination: {
      pageSize: 3,
    },
  })?.data;
  const noticias = query.noticias({
    pagination: {
      pageSize: 3,
    },
  })?.data;
  const slides = query.slides()?.data;
  const servicios = query.servicios({
    pagination: {
      pageSize: 100,
    },
    filters: {
      categoria: {
        in: [
          ENUM_SERVICIO_CATEGORIA.ahorro,
          ENUM_SERVICIO_CATEGORIA.prestamos,
          ENUM_SERVICIO_CATEGORIA.facilidades,
        ],
      },
    },
  })?.data;

  if (query.$state.isLoading) {
    return <Loading full />;
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <HomeCover portada={home?.portada} />
        <HomeSlider slides={slides} />
        <HomeServicios {...{ servicios }} />
        <HomeSocio {...{ home }} />
        <HomeAcademy posts={posts} />
        <HomeNews noticias={noticias} />
        <HomePromo {...{ home }} />
      </Layout>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<HomeProps> = async (_ctx: any) => {
  const { cacheSnapshot } = await prepareReactRender(<Home />);

  return {
    props: { cacheSnapshot },
  };
};
